# Site settings
title: Leonardo Leon
description: 'Blog'
url: 'https://leo2105.github.io/website/'
baseurl: ''
profilepic: '/images/leonardo-leon.png'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Leonardo Leon'
  email: lleonv@uni.pe
  twitter_username: _lleonv
  facebook_username: Lleonv20
  github_username:  leo2105
  linkedin_username:  lleonv
  #meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
